FROM node:20-slim

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install --location=global pnpm

WORKDIR /frontend

# Create node user and set permissions
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs
RUN chown -R nestjs:nodejs /frontend

# Switch to non-root user
USER nestjs

# Copy package files
COPY --chown=nestjs:nodejs package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy source code
COPY --chown=nest:nodejs . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["pnpm", "run", "dev", "--host"]