services:
  web-client:
    container_name: web-client-prod
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - web-api
    profiles:
      - prod

  web-api:
    container_name: web-api-prod
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8000/api/users/ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - prod