services:

  # Development frontend service
  web-client-dev:
    container_name: web-client-dev-container
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    user: "nestjs:nodejs"
    restart: unless-stopped
    develop:
      watch:
        - path: ./frontend/src
          target: /frontend/src
          action: sync
    profiles:
      - dev

  # Develpment backend service
  web-api-dev:
    container_name: web-api-dev-container
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    develop:
      watch:
        # Watch source code
        - path: ./backend/src
          target: /app/src
          action: sync
    depends_on:
      - db
    profiles:
      - dev

  # Production service - WPI
  app-prod:
    container_name: app-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - prod

  #Database service
  db:
    container_name: db-container
    image: postgres:17-alpine
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  #pgAdmin service
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    env_file:
      - ./backend/.env
    ports:
      - '5050:80'
    restart: unless-stopped
    depends_on:
      db :
        condition: service_healthy


volumes:
  db-data:
