services:
  # Development frontend service
  web-client-dev:
    container_name: web-client-dev-container
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - frontend-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    user: 'nestjs:nodejs'
    restart: unless-stopped
    develop:
      watch:
        - path: ./frontend/src
          target: /frontend/src
          action: sync
    profiles:
      - dev
      - local

  # Develpment backend service
  web-api-dev:
    container_name: web-api-dev-container
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/app/backend/src
      - backend-modules:/app/node_modules
    environment:
      #- NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}
    restart: unless-stopped
    develop:
      watch:
        # Watch source code
        - path: ./backend/src
          target: /app/backend/src
          action: sync
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - dev
      - local

  #Development database service
  db:
    container_name: db-container
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST= ${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT:}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - local

  #Development pgAdmin service
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@localhost}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - local

  # Production service
  web-api-prod:
    container_name: web-api-prod-container
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - '5132:8000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8000/api/users/ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: sh -c "pnpm db:push && pnpm run start:prod"
    profiles:
      - prod
volumes:
  db-data: # Needed for dev profile
    driver: local
  frontend-modules:
    driver: local
  backend-modules:
    driver: local
  pgadmin-data:  
    driver: local
